name: 'Match against glob'
description: 'Matches filenames against glob patterns. Uses minimatch'
inputs:
  filenames:
    description: 'Filenames to test. Use comma separated list in string format'
    required: true
  patterns:
    description: 'Glob patterns to test against. Use comma separated list in string format'
    required: true
outputs:
  match: 
    description: 'True if at least one filename matches against at least one glob. False if no matches were found'
  files: 
    description: 'Lists all files matching the patterns'
runs:
  using: 'node16'
  main: 'index.js'
branding:
  icon: 'file'  
  color: 'blue'
